"""
Django settings for aitek_back project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-zkmzq81dn#h%e&r-swslsu%bm_ap&fiyql%5m858jvq(qaxfx1')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '1').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [
    item.strip()
    for item in os.environ.get(
        'DJANGO_ALLOWED_HOSTS',
        '127.0.0.1,localhost,testserver,159.75.5.97',
    ).split(',')
    if item.strip()
]

CSRF_TRUSTED_ORIGINS = [
    item.strip()
    for item in os.environ.get(
        'DJANGO_CSRF_TRUSTED_ORIGINS',
        'http://127.0.0.1:8081,http://localhost:8081,http://159.75.5.97',
    ).split(',')
    if item.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'system',
    'middleware_app',
    'ai_testcase',
    'ai_api_test',
    'ai_web_test',
    'ai_app_test',
    'ci',
    'project_config',
    'functional_test',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'middleware_app.middlewares.auth_middleware.AuthMiddleware',
    'middleware_app.middlewares.crypto_middleware.CryptoMiddleware',
]

ROOT_URLCONF = 'aitek_back.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aitek_back.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'aitek',
        'USER': 'root',
        'PASSWORD': 'Ma071014',
        'HOST': '159.75.5.97',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}

if os.environ.get('DJANGO_TEST_SQLITE') == '1':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'test.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.environ.get('DJANGO_MEDIA_ROOT', BASE_DIR / 'media'))


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# 开发环境，允许前端vue访问
CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'system.authentication.BearerTokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

# AES 加解密共享密钥（16 字节），需与前端 src/utils/crypto.js 保持一致
AES_SECRET_KEY = 'aitek-dev-aes-key16'

# 需要 AES 加解密的接口路径白名单（与前端 src/utils/cryptoApis.js 保持一致）
# 后续新增加密接口：在此列表追加路径即可
CRYPTO_API_PATHS = [
    '/api/system/login/',
    '/api/system/register/',
]

# 自研 RAG / 测试用例生成（不再依赖 WeKnora）
DEEPSEEK_API_KEY = os.environ.get('DEEPSEEK_API_KEY', '')
DEEPSEEK_BASE_URL = os.environ.get('DEEPSEEK_BASE_URL', 'https://api.deepseek.com/v1')
DEEPSEEK_CHAT_MODEL = os.environ.get('DEEPSEEK_CHAT_MODEL', 'deepseek-chat')
# 与 WeKnora 一致：本机 Ollama bge-m3:latest，1024 维
EMBEDDING_API_KEY = os.environ.get('EMBEDDING_API_KEY', '')
EMBEDDING_BASE_URL = os.environ.get('EMBEDDING_BASE_URL', 'http://127.0.0.1:11434/v1')
EMBEDDING_MODEL = os.environ.get('EMBEDDING_MODEL', 'bge-m3:latest')
EMBEDDING_USE_LOCAL = os.environ.get('EMBEDDING_USE_LOCAL', '').lower() in ('1', 'true', 'yes')
RERANK_API_KEY = os.environ.get('RERANK_API_KEY', '')
RERANK_BASE_URL = os.environ.get('RERANK_BASE_URL', '')
RAG_RETRIEVE_TOP_K = int(os.environ.get('RAG_RETRIEVE_TOP_K', '5'))
RAG_RERANK_TOP_K = int(os.environ.get('RAG_RERANK_TOP_K', '3'))
RAG_HTTP_TIMEOUT = float(os.environ.get('RAG_HTTP_TIMEOUT', '120'))

# AI 测试用例生成微服务（Flask BFF 下游）
AI_SERVICE_BASE_URL = os.environ.get('AI_SERVICE_BASE_URL', 'http://127.0.0.1:8002')
AI_SERVICE_INTERNAL_TOKEN = os.environ.get('AI_SERVICE_INTERNAL_TOKEN', 'dev-internal-token')

DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024