# Generated by Django 5.1.15 on 2026-08-20 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='显示名称')),
                ('provider', models.CharField(choices=[('deepseek', 'DeepSeek'), ('openai', 'OpenAI'), ('qwen', '通义千问'), ('moonshot', 'Moonshot'), ('zhipu', '智谱 GLM'), ('ollama', 'Ollama'), ('custom', '自定义 OpenAI 兼容')], max_length=32, verbose_name='提供商')),
                ('model', models.CharField(max_length=128, verbose_name='模型名')),
                ('base_url', models.CharField(max_length=512, verbose_name='接口地址')),
                ('api_key', models.CharField(blank=True, default='', max_length=512, verbose_name='API Key')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认模型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_configs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户大模型配置',
                'verbose_name_plural': '用户大模型配置',
                'db_table': 'system_user_llm_config',
                'ordering': ['-is_default', '-id'],
            },
        ),
    ]
