# Generated by Django 5.1.15 on 2026-09-08 09:28

import django.db.models.deletion
import functional_test.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functional_projects', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '功能测试项目',
                'verbose_name_plural': '功能测试项目',
                'db_table': 'functional_project',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RequirementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='标题')),
                ('source_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='源文件名')),
                ('file', models.FileField(upload_to=functional_test.models.requirement_upload_to, verbose_name='文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='functional_test.functionalproject', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_documents', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '需求文档',
                'verbose_name_plural': '需求文档',
                'db_table': 'functional_requirement_document',
                'ordering': ['-id'],
            },
        ),
    ]
