# Generated by Django 5.1.15 on 2026-09-08 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functional_test', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(blank=True, default='', verbose_name='生成问题')),
                ('answer_raw', models.TextField(blank=True, default='', verbose_name='原始回答')),
                ('thinking', models.TextField(blank=True, default='', verbose_name='思考过程')),
                ('references', models.JSONField(blank=True, default=list, verbose_name='引用')),
                ('llm_config_id', models.IntegerField(blank=True, null=True, verbose_name='模型配置 ID')),
                ('status', models.CharField(choices=[('completed', '已完成'), ('failed', '失败')], default='completed', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase_generations', to='functional_test.functionalproject', verbose_name='项目')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase_generations', to='functional_test.requirementdocument', verbose_name='需求文档')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase_generations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '测试用例生成记录',
                'verbose_name_plural': '测试用例生成记录',
                'db_table': 'functional_testcase_generation',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FunctionalTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(blank=True, default='', max_length=64, verbose_name='用例编号')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='标题')),
                ('precondition', models.TextField(blank=True, default='', verbose_name='前置条件')),
                ('steps', models.TextField(blank=True, default='', verbose_name='测试步骤')),
                ('expected_result', models.TextField(blank=True, default='', verbose_name='预期结果')),
                ('priority', models.CharField(blank=True, default='', max_length=32, verbose_name='优先级')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functional_testcases', to='functional_test.functionalproject', verbose_name='项目')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functional_testcases', to='functional_test.requirementdocument', verbose_name='需求文档')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functional_testcases', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='functional_test.testcasegeneration', verbose_name='生成记录')),
            ],
            options={
                'verbose_name': '功能测试用例',
                'verbose_name_plural': '功能测试用例',
                'db_table': 'functional_testcase',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
