# Generated by Django 5.1.15 on 2026-08-20 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weknora_session_id', models.CharField(max_length=64, unique=True, verbose_name='WeKnora 会话 ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_testcase_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI 测试用例会话',
                'verbose_name_plural': 'AI 测试用例会话',
                'db_table': 'ai_testcase_session',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_kb_id', models.CharField(max_length=64, verbose_name='需求文档知识库 ID')),
                ('requirement_kb_name', models.CharField(blank=True, default='', max_length=255, verbose_name='需求文档知识库名称')),
                ('testcase_kb_id', models.CharField(max_length=64, verbose_name='测试用例知识库 ID')),
                ('testcase_kb_name', models.CharField(blank=True, default='', max_length=255, verbose_name='测试用例知识库名称')),
                ('agent_id', models.CharField(default='builtin-smart-reasoning', max_length=64, verbose_name='智能体 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_testcase_qas', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_configs', to='ai_testcase.testcasesession', verbose_name='会话')),
            ],
            options={
                'verbose_name': 'AI 测试用例智能推理问答',
                'verbose_name_plural': 'AI 测试用例智能推理问答',
                'db_table': 'ai_testcase_qa',
                'ordering': ['-id'],
            },
        ),
    ]
