# Generated by Django 5.1.15 on 2026-08-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clear_legacy_qa(apps, schema_editor):
    TestCaseQA = apps.get_model('ai_testcase', 'TestCaseQA')
    TestCaseQA.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ai_testcase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(clear_legacy_qa, migrations.RunPython.noop),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('kb_type', models.CharField(choices=[('requirement', '需求文档知识库'), ('testcase', '测试用例知识库')], max_length=32, verbose_name='类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_testcase_knowledge_bases', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库',
                'db_table': 'ai_testcase_knowledge_base',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ai_testcase.knowledgebase', verbose_name='知识库')),
            ],
            options={
                'verbose_name': '知识文档',
                'verbose_name_plural': '知识文档',
                'db_table': 'ai_testcase_knowledge_document',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='分块内容')),
                ('vector', models.JSONField(default=list, verbose_name='向量')),
                ('chunk_index', models.PositiveIntegerField(default=0, verbose_name='分块序号')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_testcase.knowledgedocument', verbose_name='文档')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_testcase.knowledgebase', verbose_name='知识库')),
            ],
            options={
                'verbose_name': '知识分块',
                'verbose_name_plural': '知识分块',
                'db_table': 'ai_testcase_knowledge_chunk',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='testcasesession',
            name='weknora_session_id',
        ),
        migrations.RemoveField(
            model_name='testcaseqa',
            name='agent_id',
        ),
        migrations.RemoveField(
            model_name='testcaseqa',
            name='requirement_kb_id',
        ),
        migrations.RemoveField(
            model_name='testcaseqa',
            name='requirement_kb_name',
        ),
        migrations.RemoveField(
            model_name='testcaseqa',
            name='testcase_kb_id',
        ),
        migrations.RemoveField(
            model_name='testcaseqa',
            name='testcase_kb_name',
        ),
        migrations.AddField(
            model_name='testcaseqa',
            name='requirement_kb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_qas', to='ai_testcase.knowledgebase', verbose_name='需求文档知识库'),
        ),
        migrations.AddField(
            model_name='testcaseqa',
            name='testcase_kb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase_qas', to='ai_testcase.knowledgebase', verbose_name='测试用例知识库'),
        ),
    ]
