# Generated by Django 6.1 on 2026-08-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='KEY')),
                ('value', models.TextField(verbose_name='VALUE')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='CREATE_TIME')),
            ],
            options={
                'verbose_name': '项目配置',
                'verbose_name_plural': '项目配置',
                'db_table': 'project_config',
                'ordering': ['-id'],
            },
        ),
    ]
