# Generated by Django 5.1.15 on 2026-09-15 12:49

import ai_api_test.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('functional_test', '0004_generation_pipeline_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='唯一标识')),
                ('name', models.CharField(max_length=255, verbose_name='接口名称')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=16, verbose_name='方法')),
                ('url', models.CharField(blank=True, default='', max_length=2048, verbose_name='请求地址')),
                ('path', models.CharField(blank=True, default='', max_length=1024, verbose_name='路径')),
                ('host', models.CharField(blank=True, default='', max_length=255, verbose_name='Host')),
                ('protocol', models.CharField(blank=True, default='https', max_length=16, verbose_name='协议')),
                ('version', models.CharField(blank=True, default='', max_length=64, verbose_name='版本号')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('headers', models.JSONField(blank=True, default=list, verbose_name='请求头')),
                ('query_params', models.JSONField(blank=True, default=list, verbose_name='Query 参数')),
                ('path_params', models.JSONField(blank=True, default=list, verbose_name='Path 参数')),
                ('body_mode', models.CharField(choices=[('none', 'none'), ('raw', 'raw'), ('json', 'json'), ('form-data', 'form-data'), ('urlencoded', 'urlencoded')], default='none', max_length=32, verbose_name='请求体类型')),
                ('body_raw', models.TextField(blank=True, default='', verbose_name='请求体')),
                ('body_form', models.JSONField(blank=True, default=list, verbose_name='表单参数')),
                ('auth_type', models.CharField(choices=[('none', 'none'), ('bearer', 'bearer'), ('basic', 'basic'), ('apikey', 'apikey')], default='none', max_length=32, verbose_name='鉴权类型')),
                ('auth_config', models.JSONField(blank=True, default=dict, verbose_name='鉴权配置')),
                ('content_type', models.CharField(blank=True, default='', max_length=128, verbose_name='Content-Type')),
                ('timeout_ms', models.PositiveIntegerField(default=30000, verbose_name='超时(ms)')),
                ('request_example', models.TextField(blank=True, default='', verbose_name='请求示例')),
                ('response_status', models.CharField(blank=True, default='', max_length=16, verbose_name='响应状态码')),
                ('response_headers', models.JSONField(blank=True, default=list, verbose_name='响应头')),
                ('response_body', models.TextField(blank=True, default='', verbose_name='响应体示例')),
                ('source_type', models.CharField(choices=[('manual', '手动创建'), ('openapi', 'OpenAPI/Swagger'), ('postman', 'Postman')], default='manual', max_length=32, verbose_name='来源')),
                ('source_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='源文件名')),
                ('source_file', models.FileField(blank=True, null=True, upload_to=ai_api_test.models.api_doc_upload_to, verbose_name='源文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_interfaces', to='functional_test.functionalproject', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_interfaces', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '接口',
                'verbose_name_plural': '接口',
                'db_table': 'api_interface',
                'ordering': ['-id'],
            },
        ),
    ]
