# Generated by Django 5.1.15 on 2026-09-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_api_test', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinterface',
            name='source_type',
            field=models.CharField(
                choices=[
                    ('manual', '手动创建'),
                    ('openapi', 'OpenAPI/Swagger'),
                    ('postman', 'Postman'),
                    ('word', 'Word 文档'),
                ],
                default='manual',
                max_length=32,
                verbose_name='来源',
            ),
        ),
        migrations.CreateModel(
            name='ApiInterfaceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='数据描述')),
                ('payload', models.JSONField(default=dict, verbose_name='数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('interface', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='test_data',
                    to='ai_api_test.apiinterface',
                    verbose_name='关联接口',
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='api_interface_data',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='用户',
                )),
            ],
            options={
                'verbose_name': '接口测试数据',
                'verbose_name_plural': '接口测试数据',
                'db_table': 'api_interface_data',
                'ordering': ['-id'],
            },
        ),
    ]
