# Generated by Django 5.1.15 on 2026-09-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_api_test', '0002_apiinterfacedata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='用例名称')),
                ('priority', models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], default='P2', max_length=8, verbose_name='优先级')),
                ('case_type', models.CharField(blank=True, default='正向', max_length=32, verbose_name='用例类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='用例描述')),
                ('preconditions', models.TextField(blank=True, default='', verbose_name='前置条件')),
                ('request_headers', models.JSONField(blank=True, default=list, verbose_name='请求头')),
                ('request_query', models.JSONField(blank=True, default=list, verbose_name='Query')),
                ('request_body', models.TextField(blank=True, default='', verbose_name='请求体')),
                ('expected_status', models.CharField(blank=True, default='200', max_length=16, verbose_name='期望状态码')),
                ('expected_body', models.TextField(blank=True, default='', verbose_name='期望响应')),
                ('assertions', models.JSONField(blank=True, default=list, verbose_name='断言')),
                ('source_type', models.CharField(choices=[('llm', '大模型生成'), ('manual', '手动创建')], default='llm', max_length=32, verbose_name='来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('interface', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='test_cases',
                    to='ai_api_test.apiinterface',
                    verbose_name='关联接口',
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='api_test_cases',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='用户',
                )),
            ],
            options={
                'verbose_name': '接口用例',
                'verbose_name_plural': '接口用例',
                'db_table': 'api_test_case',
                'ordering': ['-id'],
            },
        ),
    ]
