# Generated by Django 5.1.15 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_api_test', '0003_apitestcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinterface',
            name='cookies',
            field=models.JSONField(blank=True, default=list, verbose_name='Cookie'),
        ),
        migrations.AddField(
            model_name='apiinterface',
            name='setup_script',
            field=models.TextField(blank=True, default='', verbose_name='前置操作'),
        ),
        migrations.AddField(
            model_name='apiinterface',
            name='teardown_script',
            field=models.TextField(blank=True, default='', verbose_name='后置操作'),
        ),
    ]
