# Generated by Django 5.1.15 on 2026-09-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_api_test', '0004_interface_pre_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTestRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=64, verbose_name='运行ID')),
                ('event', models.CharField(max_length=64, verbose_name='事件')),
                ('outcome', models.CharField(choices=[('running', '执行中'), ('stopped', '结束'), ('success', '成功'), ('failure', '失败'), ('error', '错误'), ('skip', '跳过')], default='running', max_length=16, verbose_name='结果')),
                ('test_name', models.CharField(blank=True, default='', max_length=255, verbose_name='测试名')),
                ('message', models.TextField(blank=True, default='', verbose_name='说明')),
                ('traceback', models.TextField(blank=True, default='', verbose_name='堆栈')),
                ('screenshot_path', models.CharField(blank=True, default='', max_length=1024, verbose_name='截图路径')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='执行数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='ai_api_test.apitestcase', verbose_name='用例')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_test_run_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '接口用例执行日志',
                'verbose_name_plural': '接口用例执行日志',
                'db_table': 'api_test_run_log',
                'ordering': ['id'],
            },
        ),
    ]
