# Generated by Django 5.1.15 on 2026-09-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_suite_run_tables(apps, schema_editor):
    from ai_api_test.models import ApiTestRun, ApiTestRunStepResult, ApiTestSuiteStep

    schema_editor.create_model(ApiTestSuiteStep)
    schema_editor.create_model(ApiTestRun)
    schema_editor.create_model(ApiTestRunStepResult)


def drop_suite_run_tables(apps, schema_editor):
    from ai_api_test.models import ApiTestRun, ApiTestRunStepResult, ApiTestSuiteStep

    schema_editor.delete_model(ApiTestRunStepResult)
    schema_editor.delete_model(ApiTestRun)
    schema_editor.delete_model(ApiTestSuiteStep)


class Migration(migrations.Migration):

    dependencies = [
        ('ai_api_test', '0006_suite_and_run'),
        ('functional_test', '0004_generation_pipeline_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_suite_run_tables, drop_suite_run_tables),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='ApiTestSuiteStep',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('order', models.PositiveIntegerField(default=1, verbose_name='顺序')),
                        ('extractors', models.JSONField(blank=True, default=list, verbose_name='变量提取')),
                        ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suite_steps', to='ai_api_test.apitestcase', verbose_name='用例')),
                        ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ai_api_test.apitestsuite', verbose_name='套件')),
                    ],
                    options={
                        'verbose_name': '套件步骤',
                        'verbose_name_plural': '套件步骤',
                        'db_table': 'api_test_suite_step',
                        'ordering': ['order', 'id'],
                    },
                ),
                migrations.CreateModel(
                    name='ApiTestRun',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=255, verbose_name='执行名称')),
                        ('status', models.CharField(choices=[('running', '执行中'), ('success', '成功'), ('fail', '失败')], default='running', max_length=16, verbose_name='状态')),
                        ('total', models.PositiveIntegerField(default=0, verbose_name='总数')),
                        ('passed', models.PositiveIntegerField(default=0, verbose_name='通过')),
                        ('failed', models.PositiveIntegerField(default=0, verbose_name='失败')),
                        ('skipped', models.PositiveIntegerField(default=0, verbose_name='跳过')),
                        ('summary', models.TextField(blank=True, default='', verbose_name='摘要')),
                        ('service_run_id', models.CharField(blank=True, default='', max_length=64, verbose_name='服务运行ID')),
                        ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                        ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                        ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='ai_api_test.apitestcase', verbose_name='用例')),
                        ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_test_runs', to='functional_test.functionalproject', verbose_name='项目')),
                        ('suite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai_api_test.apitestsuite', verbose_name='套件')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_test_runs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                    ],
                    options={
                        'verbose_name': '接口测试执行',
                        'verbose_name_plural': '接口测试执行',
                        'db_table': 'api_test_run',
                        'ordering': ['-id'],
                    },
                ),
                migrations.CreateModel(
                    name='ApiTestRunStepResult',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('step_index', models.PositiveIntegerField(default=1, verbose_name='步骤')),
                        ('case_name', models.CharField(blank=True, default='', max_length=255, verbose_name='用例名称')),
                        ('passed', models.BooleanField(default=False, verbose_name='通过')),
                        ('http', models.JSONField(blank=True, default=dict, verbose_name='请求响应')),
                        ('extracts', models.JSONField(blank=True, default=dict, verbose_name='提取变量')),
                        ('assertion_logs', models.JSONField(blank=True, default=list, verbose_name='断言')),
                        ('result_logs', models.JSONField(blank=True, default=list, verbose_name='过程')),
                        ('screenshots', models.JSONField(blank=True, default=list, verbose_name='截图')),
                        ('unittest_output', models.TextField(blank=True, default='', verbose_name='unittest输出')),
                        ('failures', models.JSONField(blank=True, default=list, verbose_name='失败信息')),
                        ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_step_results', to='ai_api_test.apitestcase', verbose_name='用例')),
                        ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_results', to='ai_api_test.apitestrun', verbose_name='执行记录')),
                    ],
                    options={
                        'verbose_name': '执行步骤结果',
                        'verbose_name_plural': '执行步骤结果',
                        'db_table': 'api_test_run_step',
                        'ordering': ['step_index', 'id'],
                    },
                ),
            ],
        ),
    ]
